import { SparklesIcon } from "hugeicons-react";
import { Tooltip } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";

/**
 * Small sparkle marker with an "AI-powered" tooltip. Drop it next to any
 * feature label that is generated/assisted by AI so users know what's automated.
 */
export function AiBadge({
  label = "AI-powered — generated by AI",
  size = 12,
  className,
}: {
  label?: string;
  size?: number;
  className?: string;
}) {
  return (
    <Tooltip content={label}>
      <span
        className={cn(
          "inline-flex cursor-help items-center gap-1 rounded-full border border-indigo-500/30 bg-indigo-500/10 px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-indigo-300",
          className,
        )}>
        <SparklesIcon size={size} />
        AI
      </span>
    </Tooltip>
  );
}
